import { Product } from '@/types/Product';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Silla ergonómica de oficina',
    price: 310147,
    stock: 10,
    image: '/offers/offer-1.png',
    offer: 32,
    priceWithOffer: 210900,
  },
  {
    id: 2,
    name: 'Micrófono de estudio',
    price: 99986,
    stock: 18,
    image: '/offers/offer-2.png',
    offer: 25,
    priceWithOffer: 74990,
    isFull: true,
  },
  {
    id: 3,
    name: 'Afeitadora eléctrica más recortador',
    price: 269900,
    stock: 50,
    image: '/offers/offer-3.png',
    offer: 50,
    priceWithOffer: 134950,
  },
  {
    id: 4,
    name: 'Closet azul',
    price: 214142,
    stock: 5,
    image: '/offers/offer-4.png',
    offer: 30,
    priceWithOffer: 149900,
  },
  {
    id: 5,
    name: 'Cortina rosada',
    price: 84325,
    stock: 10,
    image: '/offers/offer-5.png',
    offer: 17,
    priceWithOffer: 69990,
    deliverPrice: 10000,
    isFull: true,
  },
];
