import { Shop } from '@/types/Shop';

export const SHOPS: Shop[] = [
  {
    id: 1,
    brand: 'Lego',
    srcLogo: '/shops/LegoLogo.png',
    srcBg: '/shops/LegoBg.png',
    altBg: 'Lego Characters',
    src: ['/shops/Lego-1.png','/shops/Lego-2.png','/shops/Lego-3.png'],
    alt: ['Lego Bike','Lego Transformer','Lego Low Eider'],
  },
  {
    id: 2,
    brand: 'Xiaomi',
    srcLogo: '/shops/XiaomiLogo.png',
    srcBg: '/shops/XiaomiBg.png',
    altBg: 'Orange Bubbles',
    src: ['/shops/Xiaomi-1.png','/shops/Xiaomi-2.png','/shops/Xiaomi-3.png'],
    alt: ['Reloj Xiaomi','Patineta eléctrica horizontal Xiaomi','Patineta eléctrica frontal Xiaomi'],
  },
  {
    id: 3,
    brand: 'Oster',
    srcLogo: '/shops/OsterLogo.png',
    srcBg: '/shops/OsterBg.png',
    altBg: 'Blur kitchen',
    src: ['/shops/Oster-1.png','/shops/Oster-2.png','/shops/Oster-3.png'],
    alt: ['Olla Oster','Licuadora Oster','Arrocera Oster'],
  },
  {
    id: 4,
    brand: 'Nikon',
    srcLogo: '/shops/NikonLogo.png',
    srcBg: '/shops/NikonBg.png',
    altBg: 'Blur kitchen',
    src: ['/shops/Nikon-1.png','/shops/Nikon-2.png','/shops/Nikon-3.png'],
    alt: ['Jack 3.5 Nikon','HDMI Nikon','Cámara Nikon'],
  },
  /* {
    id: 5,
    brand: 'Cortina rosada',
    srcLogo: '',
    srcBg: '',
    altBg: '',
    src: ['','',''],
    alt: ['','',''],
  },
  {
    id: 6,
    brand: 'Botas',
    srcLogo: '',
    srcBg: '',
    altBg: '',
    src: ['','',''],
    alt: ['','',''],
  },
  {
    id: 7,
    brand: 'Converse',
    srcLogo: '',
    srcBg: '',
    altBg: '',
    src: ['','',''],
    alt: ['','',''],
  },
  {
    id: 8,
    brand: 'Tv LG',
    srcLogo: '',
    srcBg: '',
    altBg: '',
    src: ['','',''],
    alt: ['','',''],
  },
  {
    id: 9,
    brand: 'Carpa plegable',
    srcLogo: '',
    srcBg: '',
    altBg: '',
    src: ['','',''],
    alt: ['','',''],
  },
  {
    id: 10,
    brand: 'Tennis caballero casual',
    srcLogo: '',
    srcBg: '',
    altBg: 'g',
    src: ['','',''],
    alt: ['','',''],
  }, */
];
