import { Shop } from '@/types/Shop';

export const SHOPS: Shop[] = [
  {
    id: 1,
    brand: 'Lego',
    srcLogo: '/shops/LegoLogo.png',
    srcBg: '/shops/LegoBg.png',
    altBg: 'Lego Characters',
    src: ['/shops/Lego-1.png','/shops/Lego-2.png','/shops/Lego-3.png'],
    alt: ['Lego Bike','Lego Transformer','Lego Low Eider'],
  },
  {
    id: 2,
    brand: 'Xiaomi',
    srcLogo: '/shops/XiaomiLogo.png',
    srcBg: '/shops/XiaomiBg.png',
    altBg: 'Orange Bubbles',
    src: ['/shops/Xiaomi-1.png','/shops/Xiaomi-2.png','/shops/Xiaomi-3.png'],
    alt: ['Reloj Xiaomi','Patineta eléctrica horizontal Xiaomi','Patineta eléctrica frontal Xiaomi'],
  },
  {
    id: 3,
    brand: 'Oster',
    srcLogo: '/shops/OsterLogo.png',
    srcBg: '/shops/OsterBg.png',
    altBg: 'Blur kitchen',
    src: ['/shops/Oster-1.png','/shops/Oster-2.png','/shops/Oster-3.png'],
    alt: ['Olla Oster','Licuadora Oster','Arrocera Oster'],
  },
  {
    id: 4,
    brand: 'Nikon',
    srcLogo: '/shops/NikonLogo.png',
    srcBg: '/shops/NikonBg.png',
    altBg: 'Gray background',
    src: ['/shops/Nikon-1.png','/shops/Nikon-2.png','/shops/Nikon-3.png'],
    alt: ['Jack 3.5 Nikon','HDMI Nikon','Cámara Nikon'],
  },
  {
    id: 5,
    brand: 'Adidas',
    srcLogo: '/shops/AdidasLogo.png',
    srcBg: '/shops/AdidasBg.png',
    altBg: 'Adidas',
    src: ['/shops/Adidas-1.png','/shops/Adidas-2.png','/shops/Adidas-3.png'],
    alt: ['Adidas-1','Adidas-2','Adidas-3'],
  },
  {
    id: 6,
    brand: 'BlackDecker',
    srcLogo: '/shops/BlackDeckerLogo.png',
    srcBg: '/shops/BlackDeckerBg.png',
    altBg: 'Orange Bubbles',
    src: ['/shops/BlackDecker-1.png','/shops/BlackDecker-2.png','/shops/BlackDecker-3.png'],
    alt: ['BlackDecker','BlackDecker','BlackDecker'],
  },
  {
    id: 7,
    brand: 'Epson',
    srcLogo: '/shops/EpsonLogo.png',
    srcBg: '/shops/EpsonBg.png',
    altBg: 'Blur kitchen',
    src: ['/shops/Epson-1.png','/shops/Epson-2.png','/shops/Epson-3.png'],
    alt: ['Olla Epson','Licuadora Epson','Arrocera Epson'],
  },
  {
    id: 8,
    brand: 'Mabe',
    srcLogo: '/shops/MabeLogo.png',
    srcBg: '/shops/MabeBg.png',
    altBg: 'Gray Background',
    src: ['/shops/Mabe-1.png','/shops/Mabe-2.png','/shops/Mabe-3.png'],
    alt: ['Jack 3.5 Mabe','HDMI Mabe','Cámara Mabe'],
  },
  {
    id: 9,
    brand: 'Motorola',
    srcLogo: '/shops/MotorolaLogo.png',
    srcBg: '/shops/MotorolaBg.png',
    altBg: 'Motorola Characters',
    src: ['/shops/Motorola-1.png','/shops/Motorola-2.png','/shops/Motorola-3.png'],
    alt: ['Motorola Bike','Motorola Transformer','Motorola Low Eider'],
  },
  {
    id: 10,
    brand: 'Samsung',
    srcLogo: '/shops/SamsungLogo.png',
    srcBg: '/shops/SamsungBg.png',
    altBg: 'Orange Bubbles',
    src: ['/shops/Samsung-1.png','/shops/Samsung-2.png','/shops/Samsung-3.png'],
    alt: ['Reloj Samsung','Patineta eléctrica horizontal Samsung','Patineta eléctrica frontal Samsung'],
  },
  {
    id: 11,
    brand: 'Whirlpool',
    srcLogo: '/shops/WhirlpoolLogo.png',
    srcBg: '/shops/WhirlpoolBg.png',
    altBg: 'Orange Bubbles',
    src: ['/shops/Whirlpool-1.png','/shops/Whirlpool-2.png','/shops/Whirlpool-3.png'],
    alt: ['Reloj Whirlpool','Patineta eléctrica horizontal Whirlpool','Patineta eléctrica frontal Whirlpool'],
  },
];
