import Head from "next/head";
import Header from "@/components/Header";
import { Roboto } from "next/font/google";
import Carrousel from "@/components/Carrousel";
import PaymentMethods from "@/components/PaymentMethods";
import Offers from "@/components/Offers";
import Subscribe from "@/components/Subscribe";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Mercado Libre</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main className="min-h-screen bg-gray-100">
        <Header />
        <Carrousel />
        <div className="mx-40">
          <PaymentMethods />
          <Offers />
          <Subscribe />
        </div>
      </main>
    </>
  );
}
